name: exif_lister
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  args: ^2.3.1
  exif: ^3.1.2
  #path_provider: ^2.0.11

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
